[package]
name = "xpalm"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
inquire = "0.7.5"
local-ip-address = "0.6.3"
tokio = { version = "1.41.1", features = ["full"] }
vigem-client = "0.1.4"
whoami = "1.5.2"
win-msgbox = "0.2.1"
queues = "1.1.0"